// Generated by ReMap for R5Reloaded.
// Source code: https://github.com/R5Reloaded-ReMap/ReMap
// Do not edit this file directly; rebuild it from the ReMap sources.

/*
 * ReMap game scripts
 *
 * Source lineage: rewritten from the active R5Reloaded ReMap implementation
 * and the legacy ReMap scripts.
 * Original ReMap: Zee (@AyeZeeBB on X, zee_x64 on Discord)
 * and Julefox (@Julefox_ on X, julefox on Discord).
 * This standalone ReMap rewrite was created and is maintained by Julefox.
 *
 * Made with love for the Apex modding community. <3
 * Built on the Apex modding foundation created by Amos (@AmosModz on X, amosmodz on Discord):
 * https://github.com/Mauler125/r5sdk
 */

global function ReMap_ClearClientProps
global function ReMap_CreateClientProp
global function ReMap_CreateCameraPath

struct
{
	array< entity > props
} file

void function ReMap_ClearClientProps()
{
	foreach ( entity prop in file.props )
	{
		if ( IsValid( prop ) )
			prop.Destroy()
	}

	file.props.clear()
}

entity function ReMap_CreateClientProp( asset model, vector origin, vector angles, float scale = 1.0 )
{
	entity prop = CreateClientSidePropDynamic( origin, angles, model )
	prop.SetModelScale( scale )
	file.props.append( prop )
	return prop
}

void function ReMap_CreateCameraPath( array<vector> points, array<vector> angles, float fov = 120.0, float transitionTime = 8.0, bool trackTarget = false, vector target = ZERO_VECTOR )
{
	if ( points.len() < 2 || points.len() != angles.len() )
		return
	thread ReMap_RunCameraPath( points, angles, fov, transitionTime, trackTarget, target )
}

void function ReMap_RunCameraPath( array<vector> points, array<vector> angles, float fov, float transitionTime, bool trackTarget, vector target )
{
	entity player = GetLocalClientPlayer()
	if ( !IsValid( player ) )
		return
	vector initialAngles = trackTarget ? VectorToAngles( target - points[0] ) : angles[0]
	entity camera = CreateClientSidePointCamera( points[0], initialAngles, fov )
	entity mover = CreateClientsideScriptMover( $"mdl/dev/empty_model.rmdl", points[0], initialAngles )
	camera.SetParent( mover )
	file.props.append( camera )
	file.props.append( mover )
	player.SetMenuCameraEntity( camera )

	OnThreadEnd( function() : ( player, camera, mover )
	{
		if ( IsValid( player ) )
			player.ClearMenuCameraEntity()
		if ( IsValid( camera ) )
			camera.Destroy()
		if ( IsValid( mover ) )
			mover.Destroy()
	} )

	for ( int index = 1; index < points.len(); index++ )
	{
		if ( !IsValid( mover ) )
			return
		vector destinationAngles = trackTarget ? VectorToAngles( target - points[index] ) : angles[index]
		mover.NonPhysicsMoveTo( points[index], transitionTime, 0, 0 )
		mover.NonPhysicsRotateTo( destinationAngles, transitionTime, 0, 0 )
		wait transitionTime
	}
}
