// Generated by ReMap for R5Reloaded.
// Source code: https://github.com/R5Reloaded-ReMap/ReMap
// Do not edit this file directly; rebuild it from the ReMap sources.

/*
 * ReMap game scripts
 *
 * Source lineage: rewritten from the active R5Reloaded ReMap implementation
 * and the legacy ReMap scripts.
 * Original ReMap: Zee (@AyeZeeBB on X, zee_x64 on Discord)
 * and Julefox (@Julefox_ on X, julefox on Discord).
 * This standalone ReMap rewrite was created and is maintained by Julefox.
 *
 * Made with love for the Apex modding community. <3
 * Built on the Apex modding foundation created by Amos (@AmosModz on X, amosmodz on Discord):
 * https://github.com/Mauler125/r5sdk
 */

global const bool REMAP_LOAD_MAP = false

global function Sh_ReMap_Init
global function Sh_ReMap_Clear
global function Sh_ReMap_PrecacheMap

void function Sh_ReMap_Init()
{
	if( !GetCurrentPlaylistVarBool( "remap_enable", true ) ) 
    	return

#if SERVER
	ReMap_PrecacheZiplines()
	ReMap_RegisterTextInfoPanelCallbacks()
	if ( reloadingScripts )
		ReMap_ConfigureEntProps()
	else
		AddCallback_EntitiesDidLoad( ReMap_ConfigureEntProps )
#endif
	Sh_ReMap_PrecacheMap()

#if REMAP_LOAD_MAP
#if SERVER
	AddCallback_EntitiesDidLoad( Sv_ReMap_LoadMap )
#endif // SERVER
#if CLIENT
	AddCallback_EntitiesDidLoad( Cl_ReMap_LoadMap )
#endif // CLIENT
#endif // REMAP_LOAD_MAP
}

void function Sh_ReMap_PrecacheMap()
{
	PrecacheModel( $"mdl/dev/empty.rmdl" )
}

void function Sh_ReMap_Clear()
{
#if SERVER
	ReMap_ClearProps()
	ReMap_ClearZiplines()
#elseif CLIENT
	ReMap_ClearClientProps()
#endif
}
