// Generated by ReMap for R5Reloaded.
// Source code: https://github.com/ReMap
// Do not edit this file directly; rebuild it from the ReMap sources.

/*
 * ReMap game scripts
 *
 * Source lineage: rewritten from the active R5Reloaded ReMap implementation
 * and the legacy ReMap zipline scripts.
 * Original ReMap: Zee (@AyeZeeBB on X, zee_x64 on Discord)
 * and Julefox (@Julefox_ on X, julefox on Discord).
 * This standalone ReMap rewrite was created and is maintained by Julefox.
 *
 * Made with love for the Apex modding community. <3
 * Built on the Apex modding foundation created by Amos (@AmosModz on X, amosmodz on Discord):
 * https://github.com/Mauler125/r5sdk
 */

global function ReMap_PrecacheZiplines
global function ReMap_ClearZiplines
global function ReMap_CreateZipline
global function ReMap_CreateCurvedZipline

global const int REMAP_ZIPLINE_END_NONE = 0
global const int REMAP_ZIPLINE_END_ARM = 1
global const int REMAP_ZIPLINE_END_SUPPORT = 2

const asset REMAP_ZIPLINE_MODEL_ARM = $"mdl/industrial/zipline_arm.rmdl"
const asset REMAP_ZIPLINE_MODEL_SUPPORT = $"mdl/industrial/security_fence_post.rmdl"

struct
{
	array< entity > entities
} file

void function ReMap_PrecacheZiplines()
{
	PrecacheModel( REMAP_ZIPLINE_MODEL_ARM )
	PrecacheModel( REMAP_ZIPLINE_MODEL_SUPPORT )
}

void function ReMap_ClearZiplines()
{
	foreach ( entity ent in file.entities )
	{
		if ( IsValid( ent ) )
			ent.Destroy()
	}

	file.entities.clear()
}

void function ReMap_CreateZipline( vector startOrigin, vector startAngles, vector endOrigin, vector endAngles, int startProfile = REMAP_ZIPLINE_END_ARM, int endProfile = REMAP_ZIPLINE_END_ARM, bool vertical = false, float width = 2.0, float speedScale = 1.0, float startArmHeight = 180.0, float endArmHeight = 180.0, bool pushOffInDirectionX = false, float lengthScale = 1.0, float pushOffAngle = 0.0, float fadeDistance = -1.0, float ziplineScale = 1.0, bool preserveVelocity = false, bool dropToBottom = true, float startAutoDetachDistance = 100.0, float endAutoDetachDistance = 100.0, bool restPoint = false, bool detachEndOnSpawn = false, bool detachEndOnUse = false )
{
	if ( startOrigin == endOrigin )
		return

	vector startCableOrigin = ReMap_CreateZiplineEndModel( startProfile, startOrigin, startAngles, startArmHeight )
	vector endCableOrigin = ReMap_CreateZiplineEndModel( vertical ? REMAP_ZIPLINE_END_NONE : endProfile, endOrigin, endAngles, endArmHeight )
	vector startCableAngles = startAngles
	vector endCableAngles = endAngles

	if ( vertical )
	{
		endCableOrigin = <startCableOrigin.x, startCableOrigin.y, endCableOrigin.z>
		startCableAngles = <0.0, pushOffAngle, 0.0>
		endCableAngles = startCableAngles
	}
	else
	{
		startCableAngles = VectorToAngles( Normalize( endCableOrigin - startCableOrigin ) )
		endCableAngles = VectorToAngles( Normalize( startCableOrigin - endCableOrigin ) )
	}

	entity startPoint = CreateEntity( "zipline" )
	startPoint.kv.DetachEndOnSpawn = detachEndOnSpawn ? 1 : 0
	startPoint.kv.DetachEndOnUse = detachEndOnUse ? 1 : 0
	startPoint.kv.Material = "cable/zipline.vmt"
	startPoint.kv.scale = ziplineScale
	startPoint.kv.Width = width
	startPoint.kv.ZiplineAutoDetachDistance = startAutoDetachDistance
	startPoint.kv.ZiplineDropToBottom = dropToBottom ? 1 : 0
	startPoint.kv.ZiplineFadeDistance = fadeDistance
	startPoint.kv.ZiplineLengthScale = lengthScale
	startPoint.kv.ZiplinePreserveVelocity = preserveVelocity ? 1 : 0
	startPoint.kv.ZiplinePushOffInDirectionX = pushOffInDirectionX ? 1 : 0
	startPoint.kv.ZiplineSpeedScale = speedScale
	startPoint.kv.ZiplineVersion = 3
	startPoint.kv.ZiplineVertical = vertical
	if ( restPoint )
	{
		startPoint.kv._zipline_rest_point_0 = startCableOrigin.x + " " + startCableOrigin.y + " " + startCableOrigin.z
		startPoint.kv._zipline_rest_point_1 = endCableOrigin.x + " " + endCableOrigin.y + " " + endCableOrigin.z
	}
	startPoint.SetAngles( startCableAngles )
	startPoint.SetOrigin( startCableOrigin )

	entity endPoint = CreateEntity( "zipline_end" )
	endPoint.kv.ZiplineAutoDetachDistance = endAutoDetachDistance
	endPoint.kv.ZiplinePushOffInDirectionX = pushOffInDirectionX ? 1 : 0
	endPoint.SetAngles( endCableAngles )
	endPoint.SetOrigin( endCableOrigin )

	startPoint.LinkToEnt( endPoint )
	DispatchSpawn( startPoint )
	DispatchSpawn( endPoint )
	file.entities.append( startPoint )
	file.entities.append( endPoint )
}

void function ReMap_CreateCurvedZipline( array<vector> controlPoints, int segmentsPerSpan = 8, array<int> pointProfiles = [], array<vector> pointAngles = [], array<float> pointArmHeights = [], float width = 2.0, float speedScale = 1.0 )
{
	if ( controlPoints.len() < 2 )
		return

	array<vector> adjustedPoints = clone controlPoints
	for ( int index = 0; index < adjustedPoints.len(); index++ )
	{
		int profile = index < pointProfiles.len() ? pointProfiles[index] : REMAP_ZIPLINE_END_NONE
		vector angles = index < pointAngles.len() ? pointAngles[index] : <0, 0, 0>
		float armHeight = index < pointArmHeights.len() ? pointArmHeights[index] : 180.0
		adjustedPoints[index] = ReMap_CreateCurvedZiplinePointModel( profile, adjustedPoints[index], angles, armHeight )
	}
	array<vector> curvePoints = ReMap_BuildBezierPath( adjustedPoints, segmentsPerSpan )
	if ( curvePoints.len() < 2 )
		return

	array<entity> ropes = [ ReMap_SetCurvedRopeProperties( CreateEntity( "move_rope" ), width, speedScale ) ]
	ropes[0].SetOrigin( curvePoints[0] )
	for ( int index = 1; index < curvePoints.len(); index++ )
	{
		entity rope = ReMap_SetCurvedRopeProperties( CreateEntity( "keyframe_rope" ), width, speedScale )
		rope.SetOrigin( curvePoints[index] )
		ropes.append( rope )
	}

	for ( int index = 0; index < ropes.len(); index++ )
	{
		if ( index + 1 < ropes.len() )
			ropes[index].LinkToEnt( ropes[index + 1] )
	}
	foreach ( entity rope in ropes )
	{
		DispatchSpawn( rope )
		file.entities.append( rope )
	}
}

entity function ReMap_SetCurvedRopeProperties( entity rope, float width, float speedScale )
{
	rope.kv.MoveSpeed = int( 64.0 * speedScale )
	rope.kv.Slack = 25
	rope.kv.Subdiv = "2"
	rope.kv.Width = string( width )
	rope.kv.Type = "0"
	rope.kv.TextureScale = "1"
	rope.kv.PositionInterpolator = 2
	rope.kv.RopeMaterial = "cable/zipline.vmt"
	rope.kv.Zipline = "1"
	rope.kv.ZiplineAutoDetachDistance = "150"
	rope.kv.ZiplineSagEnable = "0"
	rope.kv.ZiplineSagHeight = "50"
	rope.kv.fadedist = 50000
	return rope
}

vector function ReMap_CreateCurvedZiplinePointModel( int profile, vector origin, vector angles, float armHeight )
{
	vector armOrigin = origin
	if ( profile == REMAP_ZIPLINE_END_SUPPORT )
	{
		entity support = CreateEntity( "prop_dynamic" )
		support.SetOrigin( origin )
		support.SetAngles( angles )
		support.SetValueForModelKey( REMAP_ZIPLINE_MODEL_SUPPORT )
		support.kv.solid = SOLID_VPHYSICS
		DispatchSpawn( support )
		file.entities.append( support )
		armOrigin = origin + RotateVector( <4, -2.5, armHeight>, angles )
	}
	if ( profile != REMAP_ZIPLINE_END_ARM && profile != REMAP_ZIPLINE_END_SUPPORT )
		return origin

	entity arm = CreateEntity( "prop_dynamic" )
	arm.SetOrigin( armOrigin )
	arm.SetAngles( <angles.x, angles.y + 90.0, angles.z> )
	arm.SetValueForModelKey( REMAP_ZIPLINE_MODEL_ARM )
	arm.kv.solid = 0
	arm.kv.contents = 0
	DispatchSpawn( arm )
	file.entities.append( arm )
	return armOrigin + RotateVector( <-58, -2, -14>, angles )
}

array<vector> function ReMap_BuildBezierPath( array<vector> points, int segmentsPerSpan )
{
	if ( segmentsPerSpan < 2 )
		segmentsPerSpan = 2
	else if ( segmentsPerSpan > 32 )
		segmentsPerSpan = 32
	array<vector> tangents
	tangents.append( (points[1] - points[0]) * 0.5 )
	for ( int index = 1; index < points.len() - 1; index++ )
	{
		vector direction = points[index + 1] - points[index - 1]
		float tangentLength = min( Distance( points[index - 1], points[index] ), Distance( points[index], points[index + 1] ) ) * 0.5
		tangents.append( Length( direction ) < 0.001 ? <0, 0, 0> : Normalize( direction ) * tangentLength )
	}
	tangents.append( (points[points.len() - 1] - points[points.len() - 2]) * 0.5 )

	array<vector> curvePoints = [points[0]]
	for ( int span = 0; span < points.len() - 1; span++ )
	{
		vector p0 = points[span]
		vector p1 = p0 + tangents[span]
		vector p3 = points[span + 1]
		vector p2 = p3 - tangents[span + 1]
		for ( int segment = 1; segment <= segmentsPerSpan; segment++ )
		{
			float t = float( segment ) / float( segmentsPerSpan )
			curvePoints.append( ReMap_BezierPoint( p0, p1, p2, p3, t ) )
		}
	}
	return curvePoints
}

vector function ReMap_BezierPoint( vector p0, vector p1, vector p2, vector p3, float t )
{
	vector a = p0 + (p1 - p0) * t
	vector b = p1 + (p2 - p1) * t
	vector c = p2 + (p3 - p2) * t
	vector d = a + (b - a) * t
	vector e = b + (c - b) * t
	return d + (e - d) * t
}

vector function ReMap_CreateZiplineEndModel( int profile, vector origin, vector angles, float armHeight = 180.0 )
{
	vector armAngles = <angles.x, angles.y + 90.0, angles.z>
	if ( profile == REMAP_ZIPLINE_END_ARM )
	{
		ReMap_CreateProp( REMAP_ZIPLINE_MODEL_ARM, origin, armAngles )
		return origin + RotateVector( <-58, -2, -14>, angles )
	}
	else if ( profile == REMAP_ZIPLINE_END_SUPPORT )
	{
		ReMap_CreateProp( REMAP_ZIPLINE_MODEL_SUPPORT, origin, angles )
		vector armOrigin = origin + RotateVector( <4, -2.5, armHeight>, angles )
		ReMap_CreateProp( REMAP_ZIPLINE_MODEL_ARM, armOrigin, armAngles )
		return armOrigin + RotateVector( <-58, -2, -14>, angles )
	}

	return origin
}
